#!/bin/bash
#
# Wrapper for binary, i.e. to
# combine it with wget/curl
#
# Note: Default working directory /dev/shm, but the Kodi addon uses
# an subfolder in .kodi/userdata, i.e ( on LibreELEC)
# $HOME/.kodi/userdata/addon_data/plugin.video.simple_mediathek_de
#

BIN_NAME="${0##*/}"
BIN_NAME="${BIN_NAME%.*}.bin"  # Strip .local and add .bin
BIN_PATH="./${0%/*}"
MACH=$(uname -m)
PAUSE_KODI_PROCESS=0

if [ ! -f "${BIN_PATH}/${BIN_NAME}" ] ; then
  # Try path with architecture prefix, like x86_64.
  BIN_PATH="${0%/*}/../${MACH}/bin"
  if [ ! -f "${BIN_PATH}/${BIN_NAME}" -a "$MACH" = "armv6l" ] ; then
    BIN_PATH="${0%/*}/../armv7l/bin"
  fi
fi

# For broli libs. (Second added path for script call in 'native_sources')
LD_LIBRARY_PATH=${BIN_PATH}/../lib:../root/${MACH}/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

INDEX_FILE_FOLDER="/dev/shm/"  # Overwritten by --folder arg
VERBOSE=${VERBOSE:-0}
DEBUG=${DEBUG:-0}

# Old source for XML files
# XML_SOURCE="http://zdfmediathk.sourceforge.net/akt.xml"
# XML_DIFF_SOURCE="http://zdfmediathk.sourceforge.net/diff.xml"

# New source for XML files
XML_SOURCE="https://res.mediathekview.de/akt.xml"
XML_DIFF_SOURCE="https://res.mediathekview.de/diff.xml"

# Fetch command had to write on stdout
FETCH_WGET="wget -qO- "
FETCH_WGET="wget -O- "
FETCH_CURL="curl -L "
FETCH="${FETCH_WGET}"

# Local copies(used if DEBUG=1)
LOCAL_URL="http://localhost:8000"
DEBUG_AKT_XML="${LOCAL_URL}/Filmliste-akt.xml"
DEBUG_DIFF_XML="${LOCAL_URL}/Filmliste-diff.xml"
DEBUG_AKT_XZ="${LOCAL_URL}/Filmliste-akt.xz"
DEBUG_DIFF_XZ="${LOCAL_URL}/Filmliste-diff.xz"

echo_verbose()
{
  test "${VERBOSE}" != "0" && echoerr $@
}

echoerr() { printf "%s\n" "$*" >&2; }

# Check arguments and filter out args
# which targets this script.
parse_arguments()
{
  FILTERED_ARGS=()
  while [ "$#" -gt "0" ]
  do
    case "$1" in
      --folder)
        INDEX_FILE_FOLDER="$2"
        shift; shift
        ;;
      -f)
        INDEX_FILE_FOLDER="$2"
        shift; shift
        ;;
      --paused)
        PAUSE_KODI_PROCESS=1
        shift
        ;;
      *)
        FILTERED_ARGS+=("$1")
        shift
        ;;
    esac
  done
}

# PIPESTATUS array not available in busybox
check_shell()
{
  # EXE=`exec 2>/dev/null; readlink "/proc/$$/exe"`
  EXE=$(readlink "/proc/$$/exe")
  case "$EXE" in
    */busybox)
      echo "busybox"
      ;;
    */bash)
      echo "bash"
      ;;
    */sh)
      echo "sh"
      ;;
  esac
}

# Sends SIGSTOP or SIGCONT
# Input argument $1: 0 - continue, 1 - pause
send_signal_to_kodi()
{
  if [ "$PAUSE_KODI_PROCESS" = "1" ] ; then
    PID=$(ps | grep "[k]odi.bin" | awk 'BEGIN{FS=" "}{print $1}')

    test -n "$PID" && \
      (test "$1" = "0" -o "$1" = "Continue"  \
      && kill -s 18 $PID \
      || kill -s 19 $PID )
  fi
}

setup()
{
  # Set diff flag
  if [ "$1" = "1" -o "$1" = "diff" -o "$1" = "--diff" ] ; then
    DIFF=1
    DIFF_FLAGS="--diff"
  else
    DIFF=0
    DIFF_FLAGS=""
  fi

  if [ "$DIFF" = "1" ] ; then
    XML_SOURCE="${XML_DIFF_SOURCE}"
  fi

  if [ "$DEBUG" = "1" ] ; then
    if [ "$DIFF" = "1" ] ; then
      XML_SOURCE="${DEBUG_DIFF_XML}"
    else
      XML_SOURCE="${DEBUG_AKT_XML}"
    fi
    echo_verbose "(Debug) Use ${XML_SOURCE}"
  else
    echo_verbose "Use ${XML_SOURCE}"
  fi

  GET_XML="$FETCH ${XML_SOURCE}"

  # Get list of servers. Example entry of xml file:
  # <Server>
  #  <URL>http://m.picn.de/f/Filmliste-akt.xz</URL>
  #  <Prio>2</Prio>
  # </Server>
  XML=$( ${GET_XML} )

  # Awk script to select url with respect to the <Prio>-Tag
	# Note that mawk not support 'length(array)' and 
	# w[0], url[0] store the length of the arrays to avoid length() calls.
  URL_SELECTION='BEGIN {FS = "[<>]"; urls[0]=1; w[0]=1 }
  /\<Prio\>/ {s += $3; w[w[0]] = s; w[0] = w[0] + 1 }
  /\<URL\>/ {urls[urls[0]] = $3; urls[0] = urls[0] + 1 }
  END { if(urls[0] < 2 ){ print "error" }
else{
	w[0] = 0
  srand(); x = int(s*rand()) + 1; i=0; while( w[i] < x ) {i+=1};
  print urls[i] } }'
  #  print "i=", i, "w=", w[i], "x=", x, "url=", urls[i]  } }'

  XZ_URL=$( echo "$XML" | awk "$URL_SELECTION" )

  echo_verbose "Url: \"$XZ_URL\""

  if [ "$DEBUG" = "1" ] ; then
    if [ "$DIFF" = "1" ] ; then
      XZ_URL="${DEBUG_DIFF_XZ}"
    else
      XZ_URL="${DEBUG_AKT_XZ}"
    fi
    echo_verbose "(Debug) Url: \"$XZ_URL\""
  fi

  if [ "$XZ_URL" = "error" ] ; then
    echo_verbose "Can not parse XML file to get download url for data file."
    exit -1
  fi
}

just_print_link()
{
  # Print link for manually download..
  # DEBUG=0
  setup "$1"
  echo "${XZ_URL}"
}

update()
{ 
  setup "$1"

  GET_XZ="$FETCH ${XZ_URL}"
  UNPACK_XZ="xz -dc -"
  INDEX_JSON="${BIN_PATH}/${BIN_NAME} --index ${DIFF_FLAGS} -f ${INDEX_FILE_FOLDER}"

  echo_verbose "Call pipe is:"
  echo_verbose "${GET_XZ} | ${UNPACK_XZ} | ${INDEX_JSON}"

  # Set EXE
  EXE=$(check_shell)
  send_signal_to_kodi 1
  if [ "$EXE" = "busybox" ] ; then
    ${GET_XZ} | ${UNPACK_XZ} | ${INDEX_JSON}

    # No PIPESTATUS array available
    RET=$?
  else
    ${GET_XZ} | ${UNPACK_XZ} | ${INDEX_JSON}

    # Return status of piped commands stored in array
    eval "RET=\${PIPESTATUS[2]}\${PIPESTATUS[1]}\${PIPESTATUS[0]}"
  fi
  send_signal_to_kodi 0
  exit $RET
}

download()
{
  setup "$1"

  if [ "$2" != "" ] ; then
    FILENAME="$2"
  elif [ "${DIFF}" = "1" ] ; then
    FILENAME="${INDEX_FILE_FOLDER}Filmliste-diff.json"
  else
    FILENAME="${INDEX_FILE_FOLDER}Filmliste-akt.json"
  fi

  GET_XZ="$FETCH ${XZ_URL}"
  UNPACK_XZ="xz -dc -"
  ADD_NEWLINES="s/],\"/],\n\"/g"

  echo_verbose "Call pipe is:"
  echo_verbose "${GET_XZ} | ${UNPACK_XZ} | sed -e "${ADD_NEWLINES}" > \"${FILENAME}\""

  # Set EXE
  EXE=$(check_shell)
  send_signal_to_kodi 1
  if [ "$EXE" = "busybox" ] ; then
    ${GET_XZ} | ${UNPACK_XZ} | sed -e "${ADD_NEWLINES}" > "${FILENAME}"

    # No PIPESTATUS array available
    RET=$?
  else
    ${GET_XZ} | ${UNPACK_XZ} | sed -e "${ADD_NEWLINES}" > "${FILENAME}"

    # Return status of piped commands stored in array
    eval "RET=\${PIPESTATUS[2]}\${PIPESTATUS[1]}\${PIPESTATUS[0]}"
  fi
  send_signal_to_kodi 0
  exit $RET
}

# ====== Main ====================

if [ "$DEBUG" = "1" ] ; then
  echoerr "Script path: $BIN_PATH"
  echoerr "Binary name: $BIN_NAME"
fi

#cd $BIN_PATH
parse_arguments "$@"  # Create FILTERED_ARGS variable
set -- "${FILTERED_ARGS[@]}"  # This updates $@, $1, etc

if [ "$1" = "update" ] ; then
  update "$2"
elif [ "$1" = "link" ] ; then
  just_print_link "$2"
elif [ "$1" = "download" ] ; then
  download "$2" "$3"
else
  send_signal_to_kodi 1
  echo_verbose "${BIN_PATH}/${BIN_NAME} $@"
  ${BIN_PATH}/${BIN_NAME} "$@" --folder "$INDEX_FILE_FOLDER"
  send_signal_to_kodi 0
  exit $?
fi
